### ISSUE TITLE
Correct password is hardcoded in `server.py` as `letmein`.

### ISSUE THREAD

**Issue by Tobias-Opsahl** [NorthernTechHQ/student2023#26] opened 2023-10-24 16:54 UTC
Team: livhilde & tobias-opsahl
`server.py` checks passwords with `if username == "backdoor" and password == "letmein"`, so anyone can find the backdoor credentials.

**Comment by alfrunes** [comment] 2023-10-24 17:00
Duplicate of #21

**Closed as completed** 2023-10-24 17:02 UTC
Labels: duplicate
